import { type TextProps as RNTextProps } from "react-native";

export type TextVariant =
  | "heading18Regular"
  | "heading18Medium"
  | "heading18Semibold"
  | "heading20Regular"
  | "heading20Medium"
  | "heading20Semibold"
  | "heading24Regular"
  | "heading24Medium"
  | "heading24Semibold"
  | "heading28Regular"
  | "heading28Medium"
  | "heading28Semibold"
  | "heading32Regular"
  | "heading32Medium"
  | "heading32Semibold"
  | "heading40Regular"
  | "heading40Medium"
  | "heading40Semibold"
  | "heading52Regular"
  | "heading52Medium"
  | "heading52Semibold"
  | "subtitle20Regular"
  | "subtitle20Medium"
  | "subtitle20Semibold"
  | "subtitle20Bold"
  | "subtitle22Regular"
  | "subtitle22Medium"
  | "subtitle22Semibold"
  | "subtitle22Bold"
  | "subtitle24Regular"
  | "subtitle24Medium"
  | "subtitle24Semibold"
  | "subtitle24Bold"
  | "body16Regular"
  | "body16Medium"
  | "body16Semibold"
  | "body16Bold"
  | "body18Regular"
  | "body18Medium"
  | "body18Semibold"
  | "body18Bold"
  | "caption12Regular"
  | "caption12Medium"
  | "caption12Semibold"
  | "caption12Bold"
  | "caption13Regular"
  | "caption13Medium"
  | "caption13Semibold"
  | "caption13Bold"
  | "caption14Regular"
  | "caption14Medium"
  | "caption14Semibold"
  | "caption14Bold"
  | "caption15Regular"
  | "caption15Medium"
  | "caption15Semibold"
  | "caption15Bold";

export interface TextProps extends RNTextProps {
  className?: string;
  variant?: TextVariant;
  color?: string;
}
